user_one = {
  "username": "joakimonline",
  "password": "hejhej123",
  "firstname": "joakim",
  "lastname": "andersson",
  "image": "VÄLJ EN SNART",
  "city": "oslo",
  "address": "kirkegata 12",
  "gender": "male",
  "genderinterests": "male",
  "interests": ["sport", "gym", "fotboll", "tv", "fashion"],
  "description": "snill gogutt",
  "email": "joakim.andersson@teknologi.se",
  "phone": 12345,
  "birthday": Date,
  "friends": ["Georg Ekeberg"],
  "groups": null,
  "events": null,
  "date": Date,
  "disabilities": "celebral pares",
  "objectId": objectID,
  "governmentId": Number,
}; 